name: scrape

on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: 'DEBUG'
        required: false
        default: 'moneyman:*'
      sendNewConfigToTg:
        description: 'sendNewConfigToTg'
        required: false
        default: 'false'
  schedule:
    - cron: '0 5,13 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set container image
        id: set-container-image
        run: |
          echo "image=ghcr.io/${{ github.repository_owner }}/moneyman:latest" >> $GITHUB_OUTPUT

      - name: Pull container image
        run: docker pull ${{ steps.set-container-image.outputs.image }}

      - name: Run scraper
        run: |
          cp "$GITHUB_WORKSPACE/moneyman.conf.jsonc" "$GITHUB_WORKSPACE/config.json"
          docker run --rm \
            -v "$GITHUB_WORKSPACE/config.json:/moneyman/config.json" \
            -v "$GITHUB_WORKSPACE/config.json:/moneyman.json" \
            -e MONEYMAN_CONFIG_PATH=/moneyman.json \
            -e DEBUG="moneyman:*" \
            -e TZ="Asia/Jerusalem" \
            ${{ steps.set-container-image.outputs.image }}
