- name: Run scraper
        run: |
          echo "$MONEYMAN_CONFIG" > config.json
          docker run --rm \
            -v $(pwd)/config.json:/moneyman.json \
            -e MONEYMAN_CONFIG_PATH=/moneyman.json \
            -e DEBUG \
            -e TZ \
            -e SEND_NEW_CONFIG_TO_TG \
            ${{ steps.set-container-image.outputs.image }}
        env:
          MONEYMAN_CONFIG: ${{ secrets.MONEYMAN_CONFIG }}
          DEBUG: ${{ github.event.inputs.DEBUG || '' }}
          TZ: "Asia/Jerusalem"
          SEND_NEW_CONFIG_TO_TG: ${{ github.event.inputs.sendNewConfigToTg }}
