name: scrape

on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: 'DEBUG'
        required: false
        default: 'moneyman:*'
      sendNewConfigToTg:
        description: 'sendNewConfigToTg'
        required: false
        default: 'false'
  schedule:
    - cron: '0 5,13 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Set container image
        id: set-container-image
        run: |
          echo "image=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):latest" >> $GITHUB_OUTPUT

      - name: Pull container image
        run: docker pull ${{ steps.set-container-image.outputs.image }}

      - name: Run scraper
        env:
          RAW_CONFIG: ${{ secrets.MONEYMAN_CONFIG }}
        run: |
          COMPACT_CONFIG=$(echo "$RAW_CONFIG" | jq -c .)
          docker run --rm \
            -e MONEYMAN_CONFIG="$COMPACT_CONFIG" \
            -e DEBUG="moneyman:*" \
            -e TZ="Asia/Jerusalem" \
            -e SEND_NEW_CONFIG_TO_TG="${{ github.event.inputs.sendNewConfigToTg }}" \
            ${{ steps.set-container-image.outputs.image }}
